name: personalorganizer
description: "Personal Organizer é um aplicativo simples e eficiente para gerenciar suas tarefas diárias, compromissos e notas. Com uma interface intuitiva, ele permite organizar sua rotina e manter o foco nas atividades importantes, tudo em um único lugar."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
